baseURL = 'https://blog.diudiu.love/'
languageCode = 'zh-cn'
title = 'Bullhead‘s blog'
theme = "paper"
menu = ['main', 'footer']
[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
[params]
  github = 'bullhe4d'                  # github.com/YOUR_GITHUB_ID
  instagram = 'tzzz4444'            # instagram.com/YOUR_INSTAGRAM_ID
