baseURL = 'https://blog.diudiu.love/'
languageCode = 'zh-cn'
title = 'Bullhead'
theme = "paper"
[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
[params]
  github = 'bullhe4d'                  # github.com/YOUR_GITHUB_ID
